/**
 * Metatube API
 * Servicio interno de metatube que contiene herramientas de analisis de videos.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';


export interface Video { 
    id: string;
    title: string;
    description?: string;
    categoryId: string;
    defaultLanguage?: string;
    tags: Array<Tag>;
    publishedAt: string;
    viewCount?: number;
    likeCount?: number;
    favouriteCount?: number;
    commentCount?: number;
    duration?: string;
    definition?: string;
    caption?: string;
    channelId: string;
}

