export * from './aI.service';
import { AIService } from './aI.service';
export * from './api.service';
import { ApiService } from './api.service';
export * from './channel.service';
import { ChannelService } from './channel.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './keyWord.service';
import { KeyWordService } from './keyWord.service';
export * from './proyectos.service';
import { ProyectosService } from './proyectos.service';
export * from './topic.service';
import { TopicService } from './topic.service';
export * from './topicCategory.service';
import { TopicCategoryService } from './topicCategory.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './video.service';
import { VideoService } from './video.service';
export * from './youtube.service';
import { YoutubeService } from './youtube.service';
export * from './youtubeDatabase.service';
import { YoutubeDatabaseService } from './youtubeDatabase.service';
export const APIS = [AIService, ApiService, ChannelService, CommentsService, KeyWordService, ProyectosService, TopicService, TopicCategoryService, UsersService, VideoService, YoutubeService, YoutubeDatabaseService];
